/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_aliases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_beats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_facts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AliasesDto: {
            aliases: {
                [key: string]: string[];
            };
        };
        BeatDto: {
            added: string;
            entities: string[];
            file: string;
            id: string;
            importance?: components["schemas"]["ImportanceDto"] | null;
            importance_assessments?: components["schemas"]["ImportanceDto"][] | null;
            line?: number | null;
            metadata?: components["schemas"]["BeatMetadataDto"] | null;
            provenance?: components["schemas"]["ProvenanceDto"] | null;
            section?: components["schemas"]["SectionDto"] | null;
            source: components["schemas"]["BeatSourceDto"];
            text: string;
        };
        BeatMetadataDto: {
            mode?: string | null;
            model?: string | null;
            prompt_version?: string | null;
        };
        /** @enum {string} */
        BeatSourceDto: "llm-generated" | "manual" | "imported";
        EntitiesResponseDto: {
            aliases?: {
                [key: string]: string[];
            } | null;
            entities: string[];
        };
        EntityDetailDto: {
            beats: components["schemas"]["BeatDto"][];
            entity: string;
            facts: components["schemas"]["FactDto"][];
            timeline: components["schemas"]["TimelineEventDto"][];
        };
        /** @enum {string} */
        ExtractorKindDto: "heuristic" | "llm";
        FactDto: {
            added: string;
            category?: string | null;
            /** Format: double */
            confidence?: number | null;
            entities?: string[] | null;
            entity?: string | null;
            evidence: string[];
            fact: string;
            id: string;
            importance?: components["schemas"]["ImportanceDto"] | null;
            importance_assessments?: components["schemas"]["ImportanceDto"][] | null;
            metadata?: components["schemas"]["FactMetadataDto"] | null;
            provenance?: components["schemas"]["ProvenanceDto"] | null;
            source: components["schemas"]["FactSourceDto"];
            status?: string | null;
            timeline?: components["schemas"]["TimelineDto"] | null;
            type: components["schemas"]["FactTypeDto"];
        };
        FactMetadataDto: {
            model?: string | null;
            prompt_version?: string | null;
        };
        /** @enum {string} */
        FactSourceDto: "llm-generated" | "manual" | "imported";
        /** @enum {string} */
        FactTypeDto: "trait" | "relationship" | "knowledge" | "event" | "state";
        ImportanceDto: {
            assessed_by: components["schemas"]["ImportanceSourceDto"];
            method?: string | null;
            /** Format: double */
            score: number;
            updated: string;
        };
        /** @enum {string} */
        ImportanceSourceDto: "user" | "ai" | "heuristic";
        /** @enum {string} */
        InputModeDto: "prem" | "plain" | "markdown";
        NotesConfigDto: {
            auto_export: boolean;
            fact_categories: string[];
            lsp_integration: boolean;
        };
        NotesIndexDto: {
            entity_index: {
                [key: string]: string[];
            };
            file_index: {
                [key: string]: string[];
            };
            last_updated: string;
            schema_version: string;
            stats: components["schemas"]["NotesStatsDto"];
            story_root: string;
        };
        NotesMetadataDto: {
            config: components["schemas"]["NotesConfigDto"];
            created: string;
            modified: string;
            schema_version: string;
            title?: string | null;
        };
        NotesStatsDto: {
            beats: number;
            consistency_entries: number;
            entities_tracked: number;
            facts: number;
            timeline_events: number;
        };
        ProvenanceDto: {
            aliases_applied?: {
                [key: string]: string;
            } | null;
            normalization_steps?: string[] | null;
            normalized_with_aliases?: string[] | null;
            source_file?: string | null;
            source_line?: number | null;
        };
        RunRequestDto: {
            extractor?: components["schemas"]["ExtractorKindDto"];
            /** @example /absolute/path/to/story/story.prem */
            file: string;
            input?: components["schemas"]["InputModeDto"];
            /** Format: double */
            min_confidence?: number | null;
            /** Format: double */
            min_importance?: number | null;
            stable_ids?: boolean;
        };
        RunResponseDto: {
            ok: boolean;
            stats: components["schemas"]["NotesStatsDto"];
        };
        SectionDto: {
            act?: string | null;
            cel?: string | null;
            scene?: string | null;
        };
        StatusResponse: {
            exists: boolean;
            initialized: boolean;
            stats?: components["schemas"]["NotesStatsDto"] | null;
        };
        /** @enum {string} */
        TimelineDto: "past" | "present" | "future";
        TimelineEventDto: {
            added: string;
            entities: string[];
            event: string;
            id: string;
            order: components["schemas"]["TimelineOrderDto"];
            provenance?: components["schemas"]["ProvenanceDto"] | null;
            relative_to?: string | null;
            source: string[];
        };
        TimelineOrderDto: components["schemas"]["TimelineOrderNameDto"] | number;
        /** @enum {string} */
        TimelineOrderNameDto: "past" | "present" | "future";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_aliases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasesDto"];
                };
            };
        };
    };
    get_beats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatDto"][];
                };
            };
        };
    };
    get_entities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitiesResponseDto"];
                };
            };
        };
    };
    get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_facts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactDto"][];
                };
            };
        };
    };
    get_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotesIndexDto"];
                };
            };
        };
    };
    get_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotesMetadataDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponseDto"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_timeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventDto"][];
                };
            };
        };
    };
}
