id = "premise"
name = "Premise Language Support"
description = "Syntax highlighting and theming for Premise story files"
version = "1.0.0"
schema_version = 1
authors = ["David Lantrip <david@example.com>"]
repository = "https://github.com/lantrip/premise_grammar"
themes = ["themes/*.json"]

[grammars.premise]
repository = "https://github.com/lantrip/premise_grammar"
rev = "288b46d9c72c7b1116511fcc5efb85f01f1a2ee4"
