id = "premise"
name = "Premise Language Support"
description = "Syntax highlighting and theming for Premise story files"
version = "1.0.0"
schema_version = 1
authors = ["David Lantrip <david@example.com>"]
repository = "https://github.com/lantrip/premise_grammar"
themes = ["themes/*.json"]

# IMPORTANT: For development, we use file:// URL with local path
# For production, change to: repository = "https://github.com/lantrip/premise_grammar"
[grammars.premise]
repository = "https://github.com/lantrip/premise_grammar"
rev = "e6f0244aa416f8e165668aa00172eb1fba114195"