/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  aux_sym_line_comment_token1 = 2,
  aux_sym_file_header_token1 = 3,
  anon_sym_COLON = 4,
  anon_sym_EQ = 5,
  aux_sym_act_header_token1 = 6,
  aux_sym_act_header_token2 = 7,
  aux_sym_act_header_token3 = 8,
  anon_sym_EQ_EQ = 9,
  anon_sym_EQ_EQ_EQ = 10,
  aux_sym_cel_header_token1 = 11,
  anon_sym_DASH = 12,
  aux_sym_cel_header_token2 = 13,
  anon_sym_SLASH_SLASH_SLASH = 14,
  anon_sym_SLASH_SLASH = 15,
  anon_sym_SLASH = 16,
  anon_sym_AT = 17,
  aux_sym_entity_definition_token1 = 18,
  aux_sym_entity_definition_token2 = 19,
  aux_sym_entity_block_start_token1 = 20,
  aux_sym_entity_block_start_token2 = 21,
  anon_sym_LBRACE = 22,
  sym_entity_block_end = 23,
  anon_sym_ATimport = 24,
  anon_sym_LPAREN = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_import_statement_token1 = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_import_statement_token2 = 29,
  aux_sym_import_statement_token3 = 30,
  anon_sym_RPAREN = 31,
  aux_sym_import_statement_token4 = 32,
  aux_sym_import_statement_token5 = 33,
  anon_sym_ATadapter = 34,
  aux_sym_adapter_statement_token1 = 35,
  sym_prose_line = 36,
  sym_newline = 37,
  sym_source_file = 38,
  sym_line = 39,
  sym_line_comment = 40,
  sym_file_header = 41,
  sym_act_header = 42,
  sym_scene_header = 43,
  sym_cel_header = 44,
  sym_content_type_beat = 45,
  sym_content_type_treatment = 46,
  sym_content_type_narrative = 47,
  sym_entity_definition = 48,
  sym_entity_block_start = 49,
  sym_import_statement = 50,
  sym_adapter_statement = 51,
  sym_metadata_line = 52,
  aux_sym_source_file_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [aux_sym_file_header_token1] = "file_header_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [aux_sym_act_header_token1] = "act_header_token1",
  [aux_sym_act_header_token2] = "act_header_token2",
  [aux_sym_act_header_token3] = "act_header_token3",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ_EQ_EQ] = "===",
  [aux_sym_cel_header_token1] = "cel_header_token1",
  [anon_sym_DASH] = "-",
  [aux_sym_cel_header_token2] = "cel_header_token2",
  [anon_sym_SLASH_SLASH_SLASH] = "///",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_SLASH] = "/",
  [anon_sym_AT] = "@",
  [aux_sym_entity_definition_token1] = "entity_definition_token1",
  [aux_sym_entity_definition_token2] = "entity_definition_token2",
  [aux_sym_entity_block_start_token1] = "entity_block_start_token1",
  [aux_sym_entity_block_start_token2] = "entity_block_start_token2",
  [anon_sym_LBRACE] = "{",
  [sym_entity_block_end] = "entity_block_end",
  [anon_sym_ATimport] = "@import",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_import_statement_token1] = "import_statement_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_import_statement_token2] = "import_statement_token2",
  [aux_sym_import_statement_token3] = "import_statement_token3",
  [anon_sym_RPAREN] = ")",
  [aux_sym_import_statement_token4] = "import_statement_token4",
  [aux_sym_import_statement_token5] = "import_statement_token5",
  [anon_sym_ATadapter] = "@adapter",
  [aux_sym_adapter_statement_token1] = "adapter_statement_token1",
  [sym_prose_line] = "prose_line",
  [sym_newline] = "newline",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_line_comment] = "line_comment",
  [sym_file_header] = "file_header",
  [sym_act_header] = "act_header",
  [sym_scene_header] = "scene_header",
  [sym_cel_header] = "cel_header",
  [sym_content_type_beat] = "content_type_beat",
  [sym_content_type_treatment] = "content_type_treatment",
  [sym_content_type_narrative] = "content_type_narrative",
  [sym_entity_definition] = "entity_definition",
  [sym_entity_block_start] = "entity_block_start",
  [sym_import_statement] = "import_statement",
  [sym_adapter_statement] = "adapter_statement",
  [sym_metadata_line] = "metadata_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [aux_sym_file_header_token1] = aux_sym_file_header_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_act_header_token1] = aux_sym_act_header_token1,
  [aux_sym_act_header_token2] = aux_sym_act_header_token2,
  [aux_sym_act_header_token3] = aux_sym_act_header_token3,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ,
  [aux_sym_cel_header_token1] = aux_sym_cel_header_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_cel_header_token2] = aux_sym_cel_header_token2,
  [anon_sym_SLASH_SLASH_SLASH] = anon_sym_SLASH_SLASH_SLASH,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_entity_definition_token1] = aux_sym_entity_definition_token1,
  [aux_sym_entity_definition_token2] = aux_sym_entity_definition_token2,
  [aux_sym_entity_block_start_token1] = aux_sym_entity_block_start_token1,
  [aux_sym_entity_block_start_token2] = aux_sym_entity_block_start_token2,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [sym_entity_block_end] = sym_entity_block_end,
  [anon_sym_ATimport] = anon_sym_ATimport,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_import_statement_token1] = aux_sym_import_statement_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_import_statement_token2] = aux_sym_import_statement_token2,
  [aux_sym_import_statement_token3] = aux_sym_import_statement_token3,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_import_statement_token4] = aux_sym_import_statement_token4,
  [aux_sym_import_statement_token5] = aux_sym_import_statement_token5,
  [anon_sym_ATadapter] = anon_sym_ATadapter,
  [aux_sym_adapter_statement_token1] = aux_sym_adapter_statement_token1,
  [sym_prose_line] = sym_prose_line,
  [sym_newline] = sym_newline,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_line_comment] = sym_line_comment,
  [sym_file_header] = sym_file_header,
  [sym_act_header] = sym_act_header,
  [sym_scene_header] = sym_scene_header,
  [sym_cel_header] = sym_cel_header,
  [sym_content_type_beat] = sym_content_type_beat,
  [sym_content_type_treatment] = sym_content_type_treatment,
  [sym_content_type_narrative] = sym_content_type_narrative,
  [sym_entity_definition] = sym_entity_definition,
  [sym_entity_block_start] = sym_entity_block_start,
  [sym_import_statement] = sym_import_statement,
  [sym_adapter_statement] = sym_adapter_statement,
  [sym_metadata_line] = sym_metadata_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_header_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_act_header_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_act_header_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_act_header_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cel_header_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cel_header_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_entity_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_definition_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_block_start_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_block_start_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_entity_block_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATimport] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_statement_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_import_statement_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_statement_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ATadapter] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_adapter_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_prose_line] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_file_header] = {
    .visible = true,
    .named = true,
  },
  [sym_act_header] = {
    .visible = true,
    .named = true,
  },
  [sym_scene_header] = {
    .visible = true,
    .named = true,
  },
  [sym_cel_header] = {
    .visible = true,
    .named = true,
  },
  [sym_content_type_beat] = {
    .visible = true,
    .named = true,
  },
  [sym_content_type_treatment] = {
    .visible = true,
    .named = true,
  },
  [sym_content_type_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_entity_block_start] = {
    .visible = true,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_adapter_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 157,
        '\r', 2,
        '"', 101,
        '#', 54,
        '\'', 104,
        '(', 100,
        ')', 109,
        '-', 76,
        '/', 84,
        ':', 60,
        '=', 62,
        '@', 86,
        '{', 94,
        '}', 95,
        '\t', 1,
        ' ', 1,
        0x0b, 8,
        '\f', 8,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 157,
        '\r', 2,
        '"', 101,
        '#', 54,
        '\'', 104,
        '(', 100,
        ')', 109,
        '-', 76,
        '/', 84,
        ':', 60,
        '=', 62,
        '@', 87,
        '{', 94,
        '}', 95,
        '\t', 1,
        ' ', 1,
        0x0b, 8,
        '\f', 8,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(157);
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == '@') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(156);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(158);
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == 'a') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(159);
      if (lookahead == '#') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(160);
      if (lookahead == '@') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(101);
      if (lookahead == '\'') ADVANCE(104);
      if (lookahead == '(') ADVANCE(99);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == '@') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == 'a') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '%') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == ')') ADVANCE(68);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      if (('\n' <= lookahead && lookahead <= '\r')) ADVANCE(65);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(117);
      END_STATE();
    case 16:
      if (lookahead == '@') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(115);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 35:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '(') ADVANCE(67);
      END_STATE();
    case 36:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(103);
      END_STATE();
    case 37:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(106);
      END_STATE();
    case 38:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 39:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(79);
      END_STATE();
    case 40:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(114);
      END_STATE();
    case 41:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(75);
      END_STATE();
    case 42:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(108);
      END_STATE();
    case 43:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 45:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 156,
        '\r', 3,
        '#', 54,
        '(', 153,
        '-', 77,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 119,
        ' ', 119,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 46:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 156,
        '\r', 3,
        '#', 54,
        '(', 153,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 120,
        ' ', 120,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 47:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 156,
        '\r', 3,
        '#', 54,
        '/', 84,
        ':', 61,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 123,
        ' ', 123,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 48:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 156,
        '\r', 3,
        '#', 54,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 124,
        ' ', 124,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 49:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 158,
        '\r', 4,
        '#', 54,
        ')', 110,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 121,
        ' ', 121,
        0x0b, 127,
        '\f', 127,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 50:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 159,
        '\r', 5,
        '#', 54,
        ')', 110,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 122,
        ' ', 122,
        0x0b, 128,
        '\f', 128,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 51:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 159,
        '\r', 5,
        '#', 54,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 125,
        ' ', 125,
        0x0b, 128,
        '\f', 128,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 52:
      if (eof) ADVANCE(53);
      ADVANCE_MAP(
        '\n', 160,
        '\r', 6,
        '#', 54,
        '/', 84,
        '=', 62,
        '@', 86,
        '}', 96,
        '\t', 126,
        ' ', 126,
        0x0b, 133,
        '\f', 133,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_file_header_token1);
      if (lookahead == 's') ADVANCE(90);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_file_header_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(70);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_act_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      if (('\n' <= lookahead && lookahead <= '\r')) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_act_header_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_act_header_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '(') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_act_header_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '(') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_act_header_token3);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_act_header_token3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '=') ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '=') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_cel_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_cel_header_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '-') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_cel_header_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_cel_header_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH_SLASH);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '/') ADVANCE(80);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '/') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(82);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'a') ADVANCE(135);
      if (lookahead == 'i') ADVANCE(140);
      if (lookahead == 't') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'a') ADVANCE(135);
      if (lookahead == 'i') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_entity_definition_token1);
      if (lookahead == 's') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_entity_definition_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_entity_block_start_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(92);
      if (('\n' <= lookahead && lookahead <= '\r')) ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_entity_block_start_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_entity_block_end);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_entity_block_end);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_ATimport);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_ATimport);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_import_statement_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(103);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_import_statement_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_import_statement_token2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_import_statement_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_import_statement_token3);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(108);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(107);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_import_statement_token3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_import_statement_token4);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_import_statement_token4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_import_statement_token5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_import_statement_token5);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_ATadapter);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_ATadapter);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_adapter_statement_token1);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_adapter_statement_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        '(', 153,
        '-', 77,
        '/', 85,
        '=', 63,
        '@', 89,
        '}', 96,
        '\t', 119,
        ' ', 119,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        '(', 153,
        '/', 85,
        '=', 63,
        '@', 89,
        '}', 96,
        '\t', 120,
        ' ', 120,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        ')', 110,
        '/', 85,
        '=', 63,
        '@', 89,
        'a', 148,
        '}', 96,
        '\t', 121,
        ' ', 121,
        0x0b, 127,
        '\f', 127,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(155);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        ')', 110,
        '/', 85,
        '=', 63,
        '@', 89,
        '}', 96,
        '\t', 122,
        ' ', 122,
        0x0b, 128,
        '\f', 128,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(155);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        '/', 85,
        ':', 61,
        '=', 63,
        '@', 89,
        '}', 96,
        '\t', 123,
        ' ', 123,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '#') ADVANCE(55);
      if (lookahead == '/') ADVANCE(85);
      if (lookahead == '=') ADVANCE(63);
      if (lookahead == '@') ADVANCE(89);
      if (lookahead == '}') ADVANCE(96);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        '/', 85,
        '=', 63,
        '@', 89,
        '}', 96,
        '\t', 125,
        ' ', 125,
        0x0b, 128,
        '\f', 128,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(155);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_prose_line);
      ADVANCE_MAP(
        '#', 55,
        '/', 85,
        '=', 63,
        '@', 88,
        '}', 96,
        '\t', 126,
        ' ', 126,
        0x0b, 133,
        '\f', 133,
      );
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(155);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '#') ADVANCE(112);
      if (lookahead == 'a') ADVANCE(148);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(127);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '#') ADVANCE(112);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '%') ADVANCE(131);
      if (lookahead == '.') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '%') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == ')') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == ':') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '@') ADVANCE(151);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'a') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'd') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'e') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'g') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'i') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'i') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'm') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'm') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'n') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'o') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'p') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'p') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'r') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 'r') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 's') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 't') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 't') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == 't') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(108);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(107);
      if (lookahead != 0) ADVANCE(155);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_prose_line);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_prose_line);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(155);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == '@') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '#') ADVANCE(111);
      if (lookahead == 'a') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '#') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '@') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 48},
  [2] = {.lex_state = 48},
  [3] = {.lex_state = 48},
  [4] = {.lex_state = 49},
  [5] = {.lex_state = 49},
  [6] = {.lex_state = 45},
  [7] = {.lex_state = 45},
  [8] = {.lex_state = 50},
  [9] = {.lex_state = 50},
  [10] = {.lex_state = 46},
  [11] = {.lex_state = 47},
  [12] = {.lex_state = 46},
  [13] = {.lex_state = 51},
  [14] = {.lex_state = 46},
  [15] = {.lex_state = 51},
  [16] = {.lex_state = 52},
  [17] = {.lex_state = 51},
  [18] = {.lex_state = 51},
  [19] = {.lex_state = 48},
  [20] = {.lex_state = 48},
  [21] = {.lex_state = 48},
  [22] = {.lex_state = 48},
  [23] = {.lex_state = 48},
  [24] = {.lex_state = 48},
  [25] = {.lex_state = 48},
  [26] = {.lex_state = 48},
  [27] = {.lex_state = 48},
  [28] = {.lex_state = 48},
  [29] = {.lex_state = 48},
  [30] = {.lex_state = 48},
  [31] = {.lex_state = 48},
  [32] = {.lex_state = 48},
  [33] = {.lex_state = 48},
  [34] = {.lex_state = 48},
  [35] = {.lex_state = 48},
  [36] = {.lex_state = 48},
  [37] = {.lex_state = 48},
  [38] = {.lex_state = 48},
  [39] = {.lex_state = 48},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 14},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 35},
  [46] = {.lex_state = 56},
  [47] = {.lex_state = 14},
  [48] = {.lex_state = 36},
  [49] = {.lex_state = 37},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 56},
  [56] = {.lex_state = 56},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 56},
  [60] = {.lex_state = 38},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 39},
  [64] = {.lex_state = 36},
  [65] = {.lex_state = 14},
  [66] = {.lex_state = 7},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 40},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 56},
  [73] = {.lex_state = 40},
  [74] = {.lex_state = 37},
  [75] = {.lex_state = 92},
  [76] = {.lex_state = 36},
  [77] = {.lex_state = 37},
  [78] = {.lex_state = 56},
  [79] = {.lex_state = 40},
  [80] = {.lex_state = 92},
  [81] = {.lex_state = 35},
  [82] = {.lex_state = 41},
  [83] = {.lex_state = 40},
  [84] = {.lex_state = 14},
  [85] = {.lex_state = 40},
  [86] = {.lex_state = 56},
  [87] = {.lex_state = 41},
  [88] = {.lex_state = 92},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [aux_sym_file_header_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_act_header_token3] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_entity_definition_token1] = ACTIONS(1),
    [aux_sym_entity_block_start_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [sym_entity_block_end] = ACTIONS(1),
    [anon_sym_ATimport] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_import_statement_token4] = ACTIONS(1),
    [anon_sym_ATadapter] = ACTIONS(1),
    [aux_sym_adapter_statement_token1] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(70),
    [sym_line] = STATE(3),
    [sym_line_comment] = STATE(30),
    [sym_file_header] = STATE(30),
    [sym_act_header] = STATE(30),
    [sym_scene_header] = STATE(30),
    [sym_cel_header] = STATE(30),
    [sym_content_type_beat] = STATE(30),
    [sym_content_type_treatment] = STATE(30),
    [sym_content_type_narrative] = STATE(30),
    [sym_entity_definition] = STATE(30),
    [sym_entity_block_start] = STATE(30),
    [sym_import_statement] = STATE(30),
    [sym_adapter_statement] = STATE(30),
    [sym_metadata_line] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [aux_sym_file_header_token1] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(13),
    [anon_sym_SLASH_SLASH_SLASH] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(21),
    [sym_entity_block_end] = ACTIONS(23),
    [anon_sym_ATimport] = ACTIONS(25),
    [anon_sym_ATadapter] = ACTIONS(27),
    [sym_prose_line] = ACTIONS(23),
    [sym_newline] = ACTIONS(29),
  },
  [STATE(2)] = {
    [sym_line] = STATE(2),
    [sym_line_comment] = STATE(30),
    [sym_file_header] = STATE(30),
    [sym_act_header] = STATE(30),
    [sym_scene_header] = STATE(30),
    [sym_cel_header] = STATE(30),
    [sym_content_type_beat] = STATE(30),
    [sym_content_type_treatment] = STATE(30),
    [sym_content_type_narrative] = STATE(30),
    [sym_entity_definition] = STATE(30),
    [sym_entity_block_start] = STATE(30),
    [sym_import_statement] = STATE(30),
    [sym_adapter_statement] = STATE(30),
    [sym_metadata_line] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_POUND] = ACTIONS(33),
    [aux_sym_file_header_token1] = ACTIONS(36),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_EQ_EQ] = ACTIONS(42),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(45),
    [anon_sym_SLASH_SLASH_SLASH] = ACTIONS(48),
    [anon_sym_SLASH_SLASH] = ACTIONS(51),
    [anon_sym_SLASH] = ACTIONS(54),
    [anon_sym_AT] = ACTIONS(57),
    [sym_entity_block_end] = ACTIONS(60),
    [anon_sym_ATimport] = ACTIONS(63),
    [anon_sym_ATadapter] = ACTIONS(66),
    [sym_prose_line] = ACTIONS(60),
    [sym_newline] = ACTIONS(69),
  },
  [STATE(3)] = {
    [sym_line] = STATE(2),
    [sym_line_comment] = STATE(30),
    [sym_file_header] = STATE(30),
    [sym_act_header] = STATE(30),
    [sym_scene_header] = STATE(30),
    [sym_cel_header] = STATE(30),
    [sym_content_type_beat] = STATE(30),
    [sym_content_type_treatment] = STATE(30),
    [sym_content_type_narrative] = STATE(30),
    [sym_entity_definition] = STATE(30),
    [sym_entity_block_start] = STATE(30),
    [sym_import_statement] = STATE(30),
    [sym_adapter_statement] = STATE(30),
    [sym_metadata_line] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(72),
    [anon_sym_POUND] = ACTIONS(5),
    [aux_sym_file_header_token1] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(13),
    [anon_sym_SLASH_SLASH_SLASH] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(17),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_AT] = ACTIONS(21),
    [sym_entity_block_end] = ACTIONS(23),
    [anon_sym_ATimport] = ACTIONS(25),
    [anon_sym_ATadapter] = ACTIONS(27),
    [sym_prose_line] = ACTIONS(23),
    [sym_newline] = ACTIONS(74),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 1,
      aux_sym_import_statement_token3,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    ACTIONS(84), 1,
      aux_sym_import_statement_token4,
    ACTIONS(78), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [29] = 5,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      aux_sym_import_statement_token3,
    ACTIONS(92), 1,
      anon_sym_RPAREN,
    ACTIONS(94), 1,
      aux_sym_import_statement_token4,
    ACTIONS(88), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [58] = 4,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 1,
      aux_sym_act_header_token3,
    ACTIONS(102), 1,
      anon_sym_DASH,
    ACTIONS(98), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [84] = 4,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 1,
      aux_sym_act_header_token3,
    ACTIONS(110), 1,
      anon_sym_DASH,
    ACTIONS(106), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [110] = 4,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    ACTIONS(118), 1,
      aux_sym_import_statement_token4,
    ACTIONS(114), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [136] = 4,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    ACTIONS(126), 1,
      aux_sym_import_statement_token4,
    ACTIONS(122), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [162] = 3,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 1,
      aux_sym_act_header_token3,
    ACTIONS(130), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [185] = 3,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(136), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [208] = 3,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 1,
      aux_sym_act_header_token3,
    ACTIONS(142), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [231] = 3,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      aux_sym_import_statement_token4,
    ACTIONS(88), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [254] = 3,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(150), 1,
      aux_sym_act_header_token3,
    ACTIONS(148), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [277] = 3,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      aux_sym_import_statement_token4,
    ACTIONS(122), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [300] = 3,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      aux_sym_adapter_statement_token1,
    ACTIONS(154), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [323] = 3,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 1,
      aux_sym_import_statement_token4,
    ACTIONS(114), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [346] = 3,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 1,
      aux_sym_import_statement_token4,
    ACTIONS(160), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [369] = 2,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [389] = 2,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [409] = 2,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(174), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [429] = 2,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(178), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [449] = 2,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [469] = 2,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(186), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [489] = 2,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [509] = 2,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [529] = 2,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [549] = 2,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [569] = 2,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [589] = 2,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
    ACTIONS(206), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [609] = 2,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
    ACTIONS(210), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [629] = 2,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    ACTIONS(214), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [649] = 2,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
    ACTIONS(218), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [669] = 2,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [689] = 2,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
    ACTIONS(222), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [709] = 2,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
    ACTIONS(226), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [729] = 2,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [749] = 2,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [769] = 2,
    ACTIONS(228), 1,
      ts_builtin_sym_end,
    ACTIONS(230), 14,
      anon_sym_POUND,
      aux_sym_file_header_token1,
      anon_sym_EQ,
      anon_sym_EQ_EQ,
      anon_sym_EQ_EQ_EQ,
      anon_sym_SLASH_SLASH_SLASH,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH,
      anon_sym_AT,
      sym_entity_block_end,
      anon_sym_ATimport,
      anon_sym_ATadapter,
      sym_prose_line,
      sym_newline,
  [789] = 3,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
    ACTIONS(234), 1,
      anon_sym_DQUOTE,
    ACTIONS(236), 1,
      anon_sym_SQUOTE,
  [799] = 3,
    ACTIONS(238), 1,
      aux_sym_entity_definition_token1,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    ACTIONS(242), 1,
      anon_sym_SQUOTE,
  [809] = 2,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    ACTIONS(246), 1,
      anon_sym_SQUOTE,
  [816] = 2,
    ACTIONS(248), 1,
      anon_sym_COLON,
    ACTIONS(250), 1,
      aux_sym_act_header_token1,
  [823] = 2,
    ACTIONS(252), 1,
      aux_sym_entity_definition_token1,
    ACTIONS(254), 1,
      aux_sym_entity_block_start_token1,
  [830] = 1,
    ACTIONS(256), 1,
      aux_sym_act_header_token2,
  [834] = 1,
    ACTIONS(258), 1,
      aux_sym_line_comment_token1,
  [838] = 1,
    ACTIONS(260), 1,
      aux_sym_act_header_token1,
  [842] = 1,
    ACTIONS(262), 1,
      aux_sym_import_statement_token1,
  [846] = 1,
    ACTIONS(264), 1,
      aux_sym_import_statement_token2,
  [850] = 1,
    ACTIONS(266), 1,
      anon_sym_DQUOTE,
  [854] = 1,
    ACTIONS(266), 1,
      anon_sym_SQUOTE,
  [858] = 1,
    ACTIONS(268), 1,
      anon_sym_LBRACE,
  [862] = 1,
    ACTIONS(270), 1,
      anon_sym_DQUOTE,
  [866] = 1,
    ACTIONS(270), 1,
      anon_sym_SQUOTE,
  [870] = 1,
    ACTIONS(272), 1,
      aux_sym_line_comment_token1,
  [874] = 1,
    ACTIONS(274), 1,
      aux_sym_line_comment_token1,
  [878] = 1,
    ACTIONS(276), 1,
      anon_sym_DQUOTE,
  [882] = 1,
    ACTIONS(276), 1,
      anon_sym_SQUOTE,
  [886] = 1,
    ACTIONS(278), 1,
      aux_sym_line_comment_token1,
  [890] = 1,
    ACTIONS(280), 1,
      aux_sym_entity_definition_token2,
  [894] = 1,
    ACTIONS(282), 1,
      anon_sym_LBRACE,
  [898] = 1,
    ACTIONS(284), 1,
      anon_sym_COLON,
  [902] = 1,
    ACTIONS(286), 1,
      aux_sym_cel_header_token2,
  [906] = 1,
    ACTIONS(288), 1,
      aux_sym_import_statement_token1,
  [910] = 1,
    ACTIONS(290), 1,
      aux_sym_act_header_token1,
  [914] = 1,
    ACTIONS(292), 1,
      aux_sym_entity_definition_token1,
  [918] = 1,
    ACTIONS(294), 1,
      aux_sym_act_header_token1,
  [922] = 1,
    ACTIONS(296), 1,
      aux_sym_import_statement_token5,
  [926] = 1,
    ACTIONS(298), 1,
      aux_sym_entity_definition_token1,
  [930] = 1,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
  [934] = 1,
    ACTIONS(302), 1,
      aux_sym_entity_definition_token1,
  [938] = 1,
    ACTIONS(304), 1,
      aux_sym_line_comment_token1,
  [942] = 1,
    ACTIONS(306), 1,
      aux_sym_import_statement_token5,
  [946] = 1,
    ACTIONS(308), 1,
      aux_sym_import_statement_token2,
  [950] = 1,
    ACTIONS(310), 1,
      aux_sym_entity_block_start_token2,
  [954] = 1,
    ACTIONS(312), 1,
      aux_sym_import_statement_token1,
  [958] = 1,
    ACTIONS(314), 1,
      aux_sym_import_statement_token2,
  [962] = 1,
    ACTIONS(316), 1,
      aux_sym_line_comment_token1,
  [966] = 1,
    ACTIONS(318), 1,
      aux_sym_import_statement_token5,
  [970] = 1,
    ACTIONS(320), 1,
      aux_sym_entity_block_start_token2,
  [974] = 1,
    ACTIONS(322), 1,
      aux_sym_act_header_token2,
  [978] = 1,
    ACTIONS(324), 1,
      aux_sym_cel_header_token1,
  [982] = 1,
    ACTIONS(326), 1,
      aux_sym_import_statement_token5,
  [986] = 1,
    ACTIONS(328), 1,
      aux_sym_act_header_token1,
  [990] = 1,
    ACTIONS(330), 1,
      aux_sym_import_statement_token5,
  [994] = 1,
    ACTIONS(332), 1,
      aux_sym_line_comment_token1,
  [998] = 1,
    ACTIONS(334), 1,
      aux_sym_cel_header_token1,
  [1002] = 1,
    ACTIONS(336), 1,
      aux_sym_entity_block_start_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 29,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 84,
  [SMALL_STATE(8)] = 110,
  [SMALL_STATE(9)] = 136,
  [SMALL_STATE(10)] = 162,
  [SMALL_STATE(11)] = 185,
  [SMALL_STATE(12)] = 208,
  [SMALL_STATE(13)] = 231,
  [SMALL_STATE(14)] = 254,
  [SMALL_STATE(15)] = 277,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 323,
  [SMALL_STATE(18)] = 346,
  [SMALL_STATE(19)] = 369,
  [SMALL_STATE(20)] = 389,
  [SMALL_STATE(21)] = 409,
  [SMALL_STATE(22)] = 429,
  [SMALL_STATE(23)] = 449,
  [SMALL_STATE(24)] = 469,
  [SMALL_STATE(25)] = 489,
  [SMALL_STATE(26)] = 509,
  [SMALL_STATE(27)] = 529,
  [SMALL_STATE(28)] = 549,
  [SMALL_STATE(29)] = 569,
  [SMALL_STATE(30)] = 589,
  [SMALL_STATE(31)] = 609,
  [SMALL_STATE(32)] = 629,
  [SMALL_STATE(33)] = 649,
  [SMALL_STATE(34)] = 669,
  [SMALL_STATE(35)] = 689,
  [SMALL_STATE(36)] = 709,
  [SMALL_STATE(37)] = 729,
  [SMALL_STATE(38)] = 749,
  [SMALL_STATE(39)] = 769,
  [SMALL_STATE(40)] = 789,
  [SMALL_STATE(41)] = 799,
  [SMALL_STATE(42)] = 809,
  [SMALL_STATE(43)] = 816,
  [SMALL_STATE(44)] = 823,
  [SMALL_STATE(45)] = 830,
  [SMALL_STATE(46)] = 834,
  [SMALL_STATE(47)] = 838,
  [SMALL_STATE(48)] = 842,
  [SMALL_STATE(49)] = 846,
  [SMALL_STATE(50)] = 850,
  [SMALL_STATE(51)] = 854,
  [SMALL_STATE(52)] = 858,
  [SMALL_STATE(53)] = 862,
  [SMALL_STATE(54)] = 866,
  [SMALL_STATE(55)] = 870,
  [SMALL_STATE(56)] = 874,
  [SMALL_STATE(57)] = 878,
  [SMALL_STATE(58)] = 882,
  [SMALL_STATE(59)] = 886,
  [SMALL_STATE(60)] = 890,
  [SMALL_STATE(61)] = 894,
  [SMALL_STATE(62)] = 898,
  [SMALL_STATE(63)] = 902,
  [SMALL_STATE(64)] = 906,
  [SMALL_STATE(65)] = 910,
  [SMALL_STATE(66)] = 914,
  [SMALL_STATE(67)] = 918,
  [SMALL_STATE(68)] = 922,
  [SMALL_STATE(69)] = 926,
  [SMALL_STATE(70)] = 930,
  [SMALL_STATE(71)] = 934,
  [SMALL_STATE(72)] = 938,
  [SMALL_STATE(73)] = 942,
  [SMALL_STATE(74)] = 946,
  [SMALL_STATE(75)] = 950,
  [SMALL_STATE(76)] = 954,
  [SMALL_STATE(77)] = 958,
  [SMALL_STATE(78)] = 962,
  [SMALL_STATE(79)] = 966,
  [SMALL_STATE(80)] = 970,
  [SMALL_STATE(81)] = 974,
  [SMALL_STATE(82)] = 978,
  [SMALL_STATE(83)] = 982,
  [SMALL_STATE(84)] = 986,
  [SMALL_STATE(85)] = 990,
  [SMALL_STATE(86)] = 994,
  [SMALL_STATE(87)] = 998,
  [SMALL_STATE(88)] = 1002,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 5, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 6, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 6, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cel_header, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cel_header, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cel_header, 5, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cel_header, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 8, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 8, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 7, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 7, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_act_header, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_act_header, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_definition, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_definition, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_header, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scene_header, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cel_header, 7, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cel_header, 7, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adapter_statement, 5, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_adapter_statement, 5, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 9, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 9, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cel_header, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cel_header, 4, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_type_beat, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_type_beat, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_type_treatment, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_type_treatment, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content_type_narrative, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content_type_narrative, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_header, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_header, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_act_header, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_act_header, 4, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_header, 4, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scene_header, 4, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_line, 4, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_line, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block_start, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block_start, 4, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 11, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 11, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cel_header, 6, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cel_header, 6, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_definition, 6, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_definition, 6, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_comment, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adapter_statement, 7, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_adapter_statement, 7, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cel_header, 8, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cel_header, 8, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 10, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 10, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [300] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_celtax(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "celtax",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
